apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-web
spec:
  selector:
    matchLabels:
      app: application-web
  template:
    metadata:
      labels:
        app: application-web
    spec:
      containers:
      - name: application-web
        image: davicarneiro/application-web:v7
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: application-web
spec:
  selector:
    app: application-web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
